<p align="center"><b>SEGURIDAD</b></p>
<p align="justify">Se han incorporado a la seguridad del sitio medidas de prevención y contención acordes con las mejores prácticas vigentes en la industria con el fin de salvaguardar en la medida de lo posible la información contenida en nuestras bases de datos, entre las diversas medidas de Seguridad adoptadas, se encuentra la inclusión de los certificados o candados SSL que garantizan que toda información que transite a través de nuestras páginas web este encriptada y por ende protegida.   <br />
  Ninguna transmisión por Internet puede garantizar su seguridad al 100%. Una vez recibidos los datos, haremos todo lo posible para salvaguardar su seguridad en nuestros sistemas. En este tema, el equipo de colaboradores de ComprobanteDigital ha enfocado sus esfuerzos para ofrecer la tecnología más acorde a fin de ofrecerle la mayor seguridad posible y mitigar riesgos de desviaciones, adulteración, pérdida, consulta o tratamiento no autorizado de dicha información.</p>
<p align="justify"> </p>
<p align="center"><b>CONFIDENCIALIDAD DE LA INFORMACIÓN</b></p>
<p align="justify">ComprobanteDigital no vende ni alquila la información de los usuarios. Si los datos personales del usuario debieran ser compartidos con socios comerciales o patrocinantes, el usuario será notificado antes que éstos sean recogidos o transferidos. Si el usuario no desea que sus datos sean compartidos, puede decidir no utilizar un servicio determinado o no participar en algunas promociones o concursos.<br />
  ComprobanteDigital puede difundir la información del titular en casos especiales cuando a solicitud expresa de alguna autoridad, proporcionar esta información pueda servir para identificar, localizar o realizar acciones legales contra personas que pudiesen infringir las condiciones del servicio de nuestros sitios web, o causar daños o interferencia sobre los derechos de ComprobanteDigital o sus propiedades, de otros usuarios de nuestros sitios web o de cualquier otra persona que pudiese resultar perjudicada por dichas actividades. ComprobanteDigital no asume ninguna obligación de mantener confidencial cualquier otra información que el usuario proporcione por otros medios ajenos a los antes mencionados, incluyendo aquella información que el usuario proporcione a través de boletines y pláticas en línea (chats), así como la información que obtenga a través de los cookies que se describen en el inciso correspondiente, lo anterior en términos de lo establecido en el artículo 109 de la Ley Federal de los Derechos de Autor y de la fracción I, del artículo 76 bis de la Ley Federal de Protección al Consumidor.</p>
<p align="justify"> </p>
<p align="center"><b>PROTECCIÓN DE LA INFORMACIÓN PERSONAL</b></p>
<p align="justify">Le recomendamos que no revele su información personal, incluidos usuarios y contraseñas, a nadie. Sin embargo, ComprobanteDigital podría solicitar su contraseña en alguna llamada telefónica o mensaje de correo. En todo momento, el usuario es el responsable único y final de mantener en secreto su número de usuario / socio, contraseña personal, clave de acceso y número confidencial con los cuales tenga acceso a los servicios y contenidos de nuestros sitios web. Para disminuir los riesgos ComprobanteDigital recomienda al usuario salir de su cuenta y cerrar la ventana de su navegador cuando finalice su actividad, más aún si comparte su computadora con alguien o utiliza una computadora en un lugar público como una biblioteca o un café Internet.</p>
<p>&nbsp;</p>
<p align="right"><em>Contin&uacute;a en Anexo 3.</em></p>