<h2>Requisitos necesarios para obtener el servicio de Facturas Electr&oacute;nicas</h2>
<br />
<br />
<p><strong>1. CONTAR CON FIRMA ELECTR&Oacute;NICA AVANZADA (FIEL) SAT</strong></p>
<ul>
  <li>Si usted es una persona moral ya deber&iacute;a de contar con ella y si usted es persona f&iacute;sica a continuaci&oacute;n le mostramos los pasos a seguir:</li>
  <li>Para adquirir su&nbsp;<strong>Certificado de Firma Electr&oacute;nica Avanzada</strong>&nbsp;es necesario descargar e instalar en su PC el programa SOLCEDI del portal del SAT disponible&nbsp;<a href="ftp://ftp2.sat.gob.mx/asistencia_servicio_ftp/programas/solcedi/DSIC07504SOL.zip">aqu&iacute;</a>, el cual le generar&aacute; dos archivos, uno llamado llave privada que es un archivo con extensi&oacute;n o terminaci&oacute;n .KEY y un archivo llamado de requerimiento con extensi&oacute;n o terminaci&oacute;n .REQ los cuales le servir&aacute;n para tramitar su&nbsp;<strong>Firma Electr&oacute;nica Avanzada</strong>&nbsp;y el cual al final se la proporcionaran directamente en las instalaciones del SAT.</li>
  <li>Importante:<br />
    <br />
    Cree una carpeta de nombre &quot;FIEL&quot; y guarde en esa ubicaci&oacute;n los archivos generados en esta secci&oacute;n as&iacute; como sus contrase&ntilde;as ya que posteriormente ser&aacute;n utilizadas.&nbsp;<br />
    <br />
    Para una mejor organizaci&oacute;n le recomendamos no mezclar los archivos de&nbsp;<strong>Certificado de Sello Digital</strong>&nbsp;que se tramitaran posteriormente con los de esta secci&oacute;n que se refieren al&nbsp;<strong>Certificado de Firma Electr&oacute;nica Avanzada</strong>&nbsp;o&nbsp;<strong>FIEL</strong>&nbsp;ya que se suelen confundir unos con otros al ser estos iguales.<br />
    <br />
    En esta secci&oacute;n&nbsp;<strong>exclusivamente</strong>&nbsp;se generaran archivos relacionados con la&nbsp;<strong>Firma Electr&oacute;nica Avanzada</strong>&nbsp;<strong>(FIEL)</strong></li>
  <li>Para generar estos dos archivos es necesario abrir el programa&nbsp;<strong>SOLCEDI</strong>&nbsp;antes descargado y seleccionar del men&uacute;&nbsp;<strong>SISTEMA</strong>&nbsp;y a continuaci&oacute;n seleccionar el sub men&uacute; que dice<strong>REQUERIMIENTO FIEL</strong>&nbsp;y seguir los pasos. Le solicitara la siguiente informaci&oacute;n:</li>
  <li>1. RFC del contribuyente.</li>
  <li>2. CURP en el caso de personas f&iacute;sicas.</li>
  <li>3. Correo electr&oacute;nico.</li>
  <li>4. Dos contrase&ntilde;as una que sirve para revocar el&nbsp;<strong>certificado</strong>&nbsp;en caso de solicitarlo y la otra que sirve para proteger su&nbsp;<strong>llave privada</strong>&nbsp;(archivo con extensi&oacute;n .KEY).</li>
  <li>Una vez generados los archivos es necesario guardarlos en un diskette 3 media o dispositivo/memoria USB, y acudir a alguna de las Administraciones Locales de Asistencia al Contribuyente del SAT con los siguientes documentos:</li>
  <li>Formato FE: Solicitud de&nbsp;<strong>Certificado de Firma Electr&oacute;nica Avanzada</strong>, lleno e impreso por ambos lados en una sola hoja descargar formato&nbsp;<a href="http://www.sat.gob.mx/sitio_internet/e_sat/tu_firma/60_6627.html">aqu&iacute;.</a></li>
  <li>Original o copia certificada y fotocopia del acta de nacimiento, carta de naturalizaci&oacute;n o documento migratorio vigente.</li>
  <li>Original o copia certificada y fotocopia de la identificaci&oacute;n oficial (credencial para votar, pasaporte, c&eacute;dula profesional, cartilla del servicio militar&nbsp; credencial emitida por los gobiernos federal, estatal o municipal que cuente con la fotograf&iacute;a, firma y CURP del titular).</li>
  <li>Copia certificada y fotocopia del poder general del representante legal para actos de dominio o de administraci&oacute;n (Solo personas morales).</li>
  <li>Copia certificada y fotocopia del acta constitutiva de la persona moral solicitante (Solo personas morales).</li>
  <li>Al finalizar el tr&aacute;mite, recibir&aacute; una copia de su certificado digital de su firma electr&oacute;nica avanzada (archivo con extensi&oacute;n .CER) grabada en el disco magn&eacute;tico de 3 media o en el dispositivo/memoria USB con el que present&oacute; su archivo de requerimiento.</li>
  <li>*NOTA: </li>
</ul>
<p>Si usted tiene dudas puede acudir a los v&iacute;deos y/o pasos que se encuentran en esta p&aacute;gina o si requiere que una persona lo asesore paso a paso con los requerimientos subsecuentes, ll&aacute;menos y con gusto le atenderemos.</p>
<p><br />
  <strong>2. SOLICITAR SELLO DIGITAL - PASOS A SEGUIR AQUI</strong></p>
<ul>
  <li>Una vez contando con su&nbsp;<strong>Firma Electr&oacute;nica Avanzada ''Fiel''</strong>&nbsp;(archivo .CER que tramito en el paso anterior) , el siguiente paso para ser emisor de&nbsp;<strong>Comprobantes Fiscales Digitales</strong>&nbsp;o&nbsp;<strong>Facturas Electr&oacute;nicas</strong>, es contar con un&nbsp;<strong>Certificado de Sello Digital</strong>&nbsp;expedido por el&nbsp;<strong>Servicio de Administraci&oacute;n Tributaria SAT</strong>.</li>
  <li>Este&nbsp;<strong>Certificado de Sello Digital</strong>&nbsp;le permitir&aacute; acreditar la autor&iacute;a de los&nbsp;<strong>Comprobantes Fiscales Digitales</strong>&nbsp;que usted emita, y de esta manera sus clientes sabr&aacute;n que usted fue el autor de dicho<strong>Comprobante Fiscal Digital</strong>.</li>
  <li>El proceso para obtener el&nbsp;<strong>Certificado de Sello Digital</strong>&nbsp;es muy similar al de&nbsp;<strong>Firma Electr&oacute;nica Avanzada</strong>&nbsp;secci&oacute;n uno de esta p&aacute;gina, ya que, nuevamente, usted va a utilizar el programa<strong>SOLCEDI</strong>&nbsp;disponible&nbsp;<a href="ftp://ftp2.sat.gob.mx/asistencia_servicio_ftp/programas/solcedi/DSIC07504SOL.zip">aqu&iacute;.</a></li>
  <li>Importante:<br />
    <br />
    Cree una carpeta de nombre &quot;SELLO-DIGITAL&quot; y guarde en esa ubicaci&oacute;n los archivos generados en esta secci&oacute;n as&iacute; como sus contrase&ntilde;as ya que posteriormente ser&aacute;n utilizadas.&nbsp;<br />
    <br />
    Para una mejor organizaci&oacute;n le recomendamos no mezclar los archivos de&nbsp;<strong>Certificado de Sello Digital</strong>&nbsp;que se tramitaran en esta secci&oacute;n con los de la secci&oacute;n uno de esta p&aacute;gina que se refieren al&nbsp;<strong>Certificado de Firma Electr&oacute;nica Avanzada</strong>&nbsp;o&nbsp;<strong>FIEL</strong>&nbsp;ya que se suelen confundir unos con otros al ser estos iguales.<br />
    <br />
    En esta secci&oacute;n&nbsp;<strong>exclusivamente</strong>&nbsp;se generar&aacute;n archivos relacionados con el&nbsp;<strong>Certificado de Sello Digital</strong>. </li>
  <li>Instale e ingrese a la aplicaci&oacute;n&nbsp;<strong>SOLCEDI</strong>&nbsp;y seleccione del men&uacute; la opci&oacute;n&nbsp;<strong>SISTEMA</strong>&nbsp;y de clic en el submen&uacute;&nbsp;<strong>Requerimiento de Sellos</strong>, la aplicaci&oacute;n le solicitar&aacute; la ubicaci&oacute;n del&nbsp;<strong>Certificado de Firma Electr&oacute;nica Avanzada ''FIEL''</strong>(archivo con extensi&oacute;n&nbsp;<strong>.CER</strong>&nbsp;que le proporciono el&nbsp;<strong>SAT</strong>&nbsp;y que se basa en la secci&oacute;n uno de esta p&aacute;gina), capturar los campos&nbsp;<strong>Unidad o Sucursal</strong>&nbsp;el cual es informaci&oacute;n descriptiva como por ejemplo: MEXICO, MTY etc. y le indicara que ingrese una contrase&ntilde;a de revocaci&oacute;n, una vez ingresada la informaci&oacute;n solicitada dar clic en siguiente.</li>
  <li>Pasara a la pantalla de generaci&oacute;n de los archivos y le generar&aacute; dos archivos uno con extensi&oacute;n o terminaci&oacute;n&nbsp;<strong>.KEY</strong>&nbsp;que es su llave privada y otro con extensi&oacute;n o terminaci&oacute;n&nbsp;<strong>.REQ</strong>&nbsp;que es de requerimiento los cuales le servir&aacute;n para generar su&nbsp;<strong>Certificado de Sello Digital</strong>&nbsp;favor de guardarlos en la carpeta&nbsp;<strong>&quot;SELLO-DIGITAL&quot;</strong>&nbsp;mencionada anteriormente.</li>
  <li>Siga los pasos que le solicita la aplicaci&oacute;n y una vez generados los archivos seleccione la opci&oacute;n del men&uacute;&nbsp;<strong>Ensobreta Sellos</strong>.</li>
  <li>La aplicaci&oacute;n le solicitara que capture la ruta o ubicaci&oacute;n del&nbsp;<strong>Certificado de Firma Electr&oacute;nica Avanzada</strong>&nbsp;obtenida en la secci&oacute;n uno de esta p&aacute;gina (archivo con extensi&oacute;n&nbsp;<strong>.CER</strong>&nbsp;que le proporciono&nbsp;<strong>SAT</strong>&nbsp;en dispositivo USB o Diskette), especifique la ruta o ubicaci&oacute;n de la&nbsp;<strong>llave privada</strong>del&nbsp;<strong>Certificado de Firma Electr&oacute;nica Avanzada</strong>&nbsp;(archivo con extensi&oacute;n o terminaci&oacute;n&nbsp;<strong>.KEY</strong>&nbsp;obtenido en la secci&oacute;n uno de esta p&aacute;gina), capture su contrase&ntilde;a de la llave privada asignada en la secci&oacute;n uno, seleccione el archivo con extensi&oacute;n&nbsp;<strong>.REQ</strong>&nbsp;que acaba de generar en esta secci&oacute;n e indique la ruta donde quiere que se genere o se guarde el archivo de ensobretado con extensi&oacute;n o terminaci&oacute;n&nbsp;<strong>.SDG</strong>&nbsp;. Se le recomienda guarde el archivo anterior en la carpeta de&nbsp;<strong>&quot;SELLO-DIGITAL&quot;</strong></li>
  <li>Una vez obtenido el archivo con extensi&oacute;n&nbsp;<strong>.SDG</strong>&nbsp;ingresar&nbsp;<a href="https://www.acceso.sat.gob.mx/Acceso/CertiSAT.asp" target="_blank">aqu&iacute;</a>&nbsp;si al abrir el link anterior la p&aacute;gina le menciona que existe un error de certificado no se preocupe y de clic en donde dice&nbsp;<strong>Vaya a este sitio web (no recomendado)</strong>, en la p&aacute;gina que se abrir&aacute; favor de autenticarse con sus datos ya sea con su clave&nbsp;<strong>CIEC</strong>&nbsp;o puede ubicar un link en la parte inferior donde puede autenticarse con su firma&nbsp;<strong>FIEL</strong>. Al accesar seleccione del men&uacute; la opci&oacute;n&nbsp;<strong>Env&iacute;o de Solicitud de Certificados de Sello Digital</strong>, seleccione la ruta donde se ubica el archivo generado anteriormente en esta secci&oacute;n con extensi&oacute;n<strong>.SDG</strong>&nbsp;y de clic en enviar o mande el archivo.</li>
  <li>Por &uacute;ltimo una vez mandado el archivo, el&nbsp;<strong>SAT</strong>&nbsp;le proporcionara un nuevo archivo con extensi&oacute;n<strong>.CER</strong>&nbsp;que es el&nbsp;<strong>Certificado de Sello Digital</strong>&nbsp;el cual lo podr&aacute; consultar eligiendo la opci&oacute;n del men&uacute; que dice&nbsp;<strong>Recuperaci&oacute;n de certificados</strong>, ingresar su RFC y dar clic en OK. Le mostrar&aacute; una lista con los certificados tramitados y posiblemente le mostrar&aacute; 2 o m&aacute;s de ellos sin embargo hay que dar clic en el que dice de tipo&nbsp;<strong>Sello Digital</strong>&nbsp;ya que puede que le muestre el certificado de tipo&nbsp;<strong>Firma Electr&oacute;nica</strong>&nbsp;que tramitamos en la secci&oacute;n uno. Seleccionarlo y guardarlo en la carpeta de&nbsp;<strong>&quot;SELLO-DIGITAL&quot;</strong>.</li>
  <li>En este punto usted ya deber&iacute;a de contar con dos carpetas una llamada&nbsp;<strong>&quot;FIEL&quot;</strong>&nbsp;la cual deber&iacute;a de contener todos los archivos tramitados en la secci&oacute;n uno de esta p&aacute;gina as&iacute; como una carpeta de nombre&nbsp;<strong>&quot;SELLO-DIGITAL&quot;</strong>&nbsp;donde deber&iacute;a de contener todos los archivos tramitados en esta secci&oacute;n. El siguiente y &uacute;ltimo paso es&nbsp;<strong>tramitar sus folios</strong>&nbsp;y estar&aacute; listo para comenzar a&nbsp;<strong>facturar electr&oacute;nicamente</strong>. </li>
</ul>
<p><strong>3. TRAMITAR FOLIOS ELECTRONICOS - PASOS A SEGUIR AQUI</strong></p>
<ul>
  <li>Es necesario solicitar los&nbsp;<strong>folios electr&oacute;nicos</strong>&nbsp;para poder empezar a&nbsp;<strong>facturar electr&oacute;nicamente</strong>, esto lo puede realizar ingresando a la siguiente aplicaci&oacute;n del SAT de nombre&nbsp;<strong>SICOFI CSD</strong>&nbsp;la cual puede ingresar desde&nbsp;<a href="https://www.consulta.sat.gob.mx/SICOFI_WEB/moduloECFD_Plus/acceso.asp" target="_blank">aqu&iacute;</a>, si al abrir el link anterior la p&aacute;gina le menciona que existe un error de certificado no se preocupe y de clic en donde dice&nbsp;<strong>Vaya a este sitio web (no recomendado)</strong>. Tomar en cuenta que tiene que tener activado en su explorador las ventanas emergentes o com&uacute;n mente llamados Pop-ups para poder accesar.</li>
  <li>Posiblemente aparecer&aacute; una ventana de seguridad del&nbsp;<strong>SAT</strong>&nbsp;si es el caso favor de dar clic en el bot&oacute;n&nbsp;<strong>&quot;S&iacute;&quot;</strong>&nbsp;o en el bot&oacute;n&nbsp;<strong>&quot;Ejecutar&quot;</strong>&nbsp;si se le muestra una segunda ventana.</li>
  <li>Al ejecutarse la aplicaci&oacute;n le pedir&aacute; los siguientes datos RFC, contrase&ntilde;a de la&nbsp;<strong>llave privada</strong>, ruta del&nbsp;<strong>certificado de firma electr&oacute;nica avanzada</strong>&nbsp;el cual se tramito y le proporciono&nbsp;<strong>SAT</strong>&nbsp;en el dispositivo USB anteriormente en la secci&oacute;n uno de esta p&aacute;gina, y ruta o ubicaci&oacute;n del archivo de<strong>llave privada</strong>&nbsp;obtenida en la secci&oacute;n uno de esta p&aacute;gina. Estos archivos se encuentran en la carpeta de nombre &quot;FIEL&quot; si usted sigui&oacute; los pasos de la secci&oacute;n uno de esta p&aacute;gina.</li>
  <li>La aplicaci&oacute;n validara los datos e ingresara a un men&uacute; en el cual tendr&aacute; que dirigirse a la opci&oacute;n ''<strong>Solicitud de Folios''</strong>&nbsp;ah&iacute; tendr&aacute; que ingresar de nuevo la&nbsp;<strong>contrase&ntilde;a de la llave privada</strong>, la ruta o ubicaci&oacute;n del archivo de&nbsp;<strong>llave privada</strong>&nbsp;(Archivo con extensi&oacute;n&nbsp;<strong>.KEY</strong>) y la ruta o ubicaci&oacute;n del<strong>certificado de firma electr&oacute;nica</strong>&nbsp;todos estos datos y archivos son relacionados a su&nbsp;<strong>firma electr&oacute;nica avanzada</strong>&nbsp;tramitados en la secci&oacute;n uno de esta p&aacute;gina.</li>
  <li>Una vez capturados los datos anteriores simplemente asigne la serie con la que quiere que empiecen sus folios por ejemplo: A o B, el total de folios que necesite (recuerde que los folios ya no caducan as&iacute; es que puede tramitar o excederse en la cantidad solicitada).</li>
  <li>Nota: Es muy importante que al ingresar su serie y folio se posicione en la casilla siguiente inferior ya que no le generara el archivo y despu&eacute;s elija la ubicaci&oacute;n en donde se guardara dicho archivo y presione el bot&oacute;n generar archivo. </li>
  <li>Guarde el archivo que se genero en la ruta que quiera de su computadora e ingrese al men&uacute;&nbsp;<strong>env&iacute;o de archivos</strong>, especifique la ruta donde guardo el archivo anterior, escoja la opci&oacute;n del men&uacute;<strong>solicitud de folios</strong>&nbsp;y presione el bot&oacute;n enviar.</li>
  <li>Por &uacute;ltimo le mostrara una pantalla con la siguiente informaci&oacute;n: rfc, n&uacute;mero de aprobaci&oacute;n, rango de folios asignados, serie del certificado, a&ntilde;o de aprobaci&oacute;n que es recomendable la imprima. En esta etapa ya est&aacute;s listo para empezar a&nbsp;<strong>facturar electr&oacute;nicamente</strong>.</li>
</ul>